#! /bin/sh

# Loads the colours

. "${HOME}/.cache/wal/colors.sh"

# bspwm colours

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Discord

pywal-discord

# Firefox

pywalfox update

# Rofi

 ~/.config/rofi/colourChange.sh

