#! /bin/sh

# Monitor refresh rate

setroot -cursor_name left_ptr &
xrandr --output DP-0 --rate 144 &

# Sxhkd

pgrep -x sxhkd > /dev/null || sxhkd &

# Makes java apps work

export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

# Compositor

xcompmgr &

# Theme

~/.config/sxhkd/darkTheme

# Monitors

bspc monitor DP-0 -d 1 2 3 
bspc monitor DP-3 -d 4 5 6 
bspc monitor HDMI-0 -d 7 8 9

xrandr --output DP-0 --mode 1920x1080 --rate 144.00

# Polybar

echo 0 > ~/.config/polybar/no

~/.config/polybar/launch.sh

# Bspwm Config

bspc config border_width         4
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
